const paletteBleu = [
    //{ id: 1, nom: "bleu", valeur: "blue" },
    //{ id: 2, nom: "dark-bleu", valeur: "darkblue" },
    { id: 3, nom: "bleu-claire", valeur: "#ebf7ff" },
    { id: 4, nom: "bleu-electrique", valeur: "#1150d1" },
    { id: 5, nom: "bleu-royal", valeur: "#050adb" },
    { id: 6, nom: "bleu-lavande", valeur: "#5d58e6" },
    { id: 7, nom: "bleu-acier", valeur: "#4255a5" },
    { id: 8, nom: "bleu-petrole", valeur: "#2d5a86" },
    { id: 9, nom: "bleu-cobalt", valeur: "#1a299c" },
    { id: 10, nom: "bleu-gris", valeur: "#4a646d" },
    { id: 11, nom: "bleu-sarcelle", valeur: "#36626a" },
    { id: 12, nom: "bleu-ciel", valeur: "#3095e0" },
    { id: 13, nom: "bleu-saphir", valeur: "#2b8fee" },
    { id: 14, nom: "bleu-lagon", valeur: "#60d7e7" },
    { id: 15, nom: "bleu-gris-clair", valeur: "#809bb0" },
    { id: 16, nom: "bleu-lilas", valeur: "#8381fd" },
    { id: 17, nom: "bleu-nuit", valeur: "#5326d2" },
    { id: 18, nom: "bleu-turquoise", valeur: "#3e99e9" },
    { id: 19, nom: "bleu-cyan", valeur: "#3ec3de" },
    { id: 20, nom: "bleu-royal-clair", valeur: "#4279f9" },
    { id: 21, nom: "bleu-acier-fonce", valeur: "#20607b" },
    { id: 22, nom: "bleu-marine-fonce", valeur: "#0f2e51" },
    { id: 23, nom: "bleu-canard", valeur: "#1f8696" },
];
const paletteGris = [
    //{ id: 1, nom: "gris", valeur: "gray" },
    //{ id: 2, nom: "darkgray", valeur: "darkgrey" },
    { id: 3, nom: "gris-claire", valeur: "#f8f9fa" },
    //{ id: 4, nom: "gris-autre", valeur: "rgb(16, 16, 16)" },
    { id: 5, nom: "gris-claire-100", valeur: "#333" },
    { id: 6, nom: "gris-ardoise-fonce", valeur: "#2a2f34" },
    { id: 7, nom: "gris-perle", valeur: "#91a6b1" },
    { id: 8, nom: "gris-argent", valeur: "#a6b8b4" },
];
const paletteVert = [
    //{ id: 1, nom: "vert", valeur: "green" },
    { id: 2, nom: "vert-claire", valeur: "#4ffa6b80" },
    { id: 3, nom: "vert-sauge", valeur: "#729780" },
    { id: 4, nom: "vert-menthe", valeur: "#98db83" },
    { id: 5, nom: "vert-vif", valeur: "#4eaf30" },
    { id: 6, nom: "vert-citron", valeur: "#4ed414" },
    { id: 7, nom: "vert-pistache", valeur: "#c1f061" },
    { id: 8, nom: "vert-jade", valeur: "#65dd90" },
    { id: 9, nom: "vert-herbe", valeur: "#69c518" },
    { id: 10, nom: "vert-emeraude", valeur: "#058606" },
    { id: 11, nom: "vert-pomme", valeur: "#2aba10" },
    { id: 12, nom: "vert-pomme-clair", valeur: "#7ec952" },
    { id: 13, nom: "vert-lime", valeur: "#8ce732" },
    { id: 14, nom: "vert-chartreuse", valeur: "#9dd54c" },
    { id: 15, nom: "vert-mousse", valeur: "#313f05" },
    { id: 16, nom: "vert-kaki", valeur: "#759d39" },
    { id: 17, nom: "vert-neon", valeur: "#08fea2" },
    { id: 18, nom: "vert-lichen", valeur: "#8eb540" },
    { id: 19, nom: "vert-sapin", valeur: "#168b5d" },
    { id: 20, nom: "vert-olive", valeur: "#7b932b" },
    { id: 21, nom: "vert-olive-clair", valeur: "#9da383" },
    { id: 22, nom: "vert-fluo", valeur: "#5ce347" },
    { id: 23, nom: "vert-pin", valeur: "#3fa35a" },
    { id: 24, nom: "vert-menthe-pastel", valeur: "#9ce59b" },
];
const paletteRouge = [
    { id: 1, nom: "rouge-vif", valeur: "#d0181b" },
    { id: 2, nom: "rouge-rouille", valeur: "#d25e47" },
    { id: 3, nom: "rouge-bordeaux", valeur: "#923a43" },
    { id: 4, nom: "rouge-tomate", valeur: "#f0280f" },
    { id: 5, nom: "rouge-cerise", valeur: "#ff3b5d" },
];
// Autres catégories comme violet, rose, orange, jaune, etc.

export { paletteBleu, paletteGris, paletteRouge, paletteVert };