import React from "react";
import TitreDoc from "../../../composants/docs_composant/TitreDoc";
import { Archive, File, Share, TableIcon, X } from "lucide-react";
import { Bloc, Col, Table } from "../../../composants";
import Tableau from "../../../utilitaire/Tableau";

/*const dataTest = [
  {
    id: 1,
    nom: "Ngomo Mba",
    prenom: "Dann Sloann",
    age: 26,
    ecole: "BBS",
    niveau: "M1 SIB",
    quartier: "Malibé 1",
  },
  {
    id: 2,
    nom: "Othamot Mohamed Hamissou",
    prenom: "Zeïtoune",
    age: 25,
    ecole: "BBS",
    niveau: "M2 CCA",
    quartier: "Awendjé",
  },
  {
    id: 3,
    nom: "Hounsokou",
    prenom: "Arnaud Roland",
    age: 27,
    ecole: "ITA",
    niveau: "M1 ",
    quartier: "Mindoubé 1",
  },
  {
    id: 4,
    nom: "Nyingone Obieghe",
    prenom: "Grâce Orphé",
    age: 26,
    ecole: "ISP",
    niveau: "L3",
    quartier: "Ouakam",
  },
  {
    id: 5,
    nom: "Salou Konitatou Achabi Modoukpè",
    prenom: "Ola",
    age: 25,
    ecole: "UOB",
    niveau: "M1 BF",
    quartier: "Belle-vue 2",
  },
];*/

const dataTest = [
  {
    id: 1,
    nom: "Mba Ella",
    prenom: "Jules Armel",
    age: 24,
    ecole: "UOB",
    niveau: "L2 Droit",
    quartier: "Nzeng-Ayong",
  },
  {
    id: 2,
    nom: "Essono Minko",
    prenom: "Carine Estelle",
    age: 23,
    ecole: "HEM",
    niveau: "M1 Finance",
    quartier: "Glass",
  },
  {
    id: 3,
    nom: "Kombila Ndong",
    prenom: "Stéphane Junior",
    age: 28,
    ecole: "ENS",
    niveau: "M2 Lettres",
    quartier: "Louis",
  },
  {
    id: 4,
    nom: "Abessolo Mengue",
    prenom: "Nathalie Brigitte",
    age: 25,
    ecole: "UOB",
    niveau: "L3 Psychologie",
    quartier: "Pk8",
  },
  {
    id: 5,
    nom: "Onanga Ekoume",
    prenom: "Christ Hervé",
    age: 27,
    ecole: "SUP Management",
    niveau: "M2 Marketing",
    quartier: "Sotega",
  },
  {
    id: 6,
    nom: "Bivigou Ondo",
    prenom: "Prisca Aurélie",
    age: 24,
    ecole: "ISSEA",
    niveau: "M1 Statistiques",
    quartier: "Likouala",
  },
  {
    id: 7,
    nom: "Edzang Nguema",
    prenom: "Dieudonné",
    age: 29,
    ecole: "Polytech",
    niveau: "M2 Génie Civil",
    quartier: "Nzeng-Ayong",
  },
  {
    id: 8,
    nom: "Minko Nguema",
    prenom: "Linda Grâce",
    age: 22,
    ecole: "HEM",
    niveau: "L3 Comptabilité",
    quartier: "Avéa",
  },
  {
    id: 9,
    nom: "Obiang Obame",
    prenom: "Jean Pierre",
    age: 30,
    ecole: "ENSET",
    niveau: "M2 Informatique",
    quartier: "Akébé-Ville",
  },
  {
    id: 10,
    nom: "Nna Ondo",
    prenom: "Bruno Martial",
    age: 28,
    ecole: "UOB",
    niveau: "M1 Droit",
    quartier: "Beau-Séjour",
  },
  {
    id: 11,
    nom: "Ella Ovono",
    prenom: "Mireille Sandra",
    age: 25,
    ecole: "BBS",
    niveau: "M2 Audit",
    quartier: "Charbonnages",
  },
  {
    id: 12,
    nom: "Ayina Obiang",
    prenom: "Patrick Lionel",
    age: 26,
    ecole: "SUP Telecom",
    niveau: "M1 Réseaux",
    quartier: "Nzeng-Ayong",
  },
  {
    id: 13,
    nom: "Ndong Nze",
    prenom: "Eliane Paule",
    age: 23,
    ecole: "UOB",
    niveau: "L3 Économie",
    quartier: "Owendo",
  },
  {
    id: 14,
    nom: "Mengue Mba",
    prenom: "Axel Junior",
    age: 27,
    ecole: "HEM",
    niveau: "M1 Banque",
    quartier: "Melen",
  },
  {
    id: 15,
    nom: "Mvoulou Eyang",
    prenom: "Josiane Clarisse",
    age: 24,
    ecole: "ENAM",
    niveau: "M1 GRH",
    quartier: "Sotega",
  },
  {
    id: 16,
    nom: "Minko Ella",
    prenom: "Richard Stéphane",
    age: 25,
    ecole: "ITA",
    niveau: "M1 Agronomie",
    quartier: "Mikolongo",
  },
  {
    id: 17,
    nom: "Biyogo Onanga",
    prenom: "Nadine Christelle",
    age: 26,
    ecole: "ISP",
    niveau: "L3 Philosophie",
    quartier: "Batavea",
  },
  {
    id: 18,
    nom: "Ovono Edou",
    prenom: "Thierry Landry",
    age: 29,
    ecole: "UOB",
    niveau: "M2 Gestion",
    quartier: "Akanda",
  },
  {
    id: 19,
    nom: "Mengome Ndong",
    prenom: "Esther Paola",
    age: 22,
    ecole: "ENS",
    niveau: "L3 Lettres Modernes",
    quartier: "Okala",
  },
  {
    id: 20,
    nom: "Ebane Ella",
    prenom: "Yvan Brice",
    age: 28,
    ecole: "SUP Management",
    niveau: "M2 Logistique",
    quartier: "Pk12",
  },
  {
    id: 21,
    nom: "Nziengui Mba",
    prenom: "Rodolphe Ulrich",
    age: 27,
    ecole: "BBS",
    niveau: "M1 Management",
    quartier: "Mindoubé 2",
  },
  {
    id: 22,
    nom: "Ombiang Nzoghe",
    prenom: "Sylvie Christelle",
    age: 23,
    ecole: "UOB",
    niveau: "L3 Lettres",
    quartier: "Plein Ciel",
  },
  {
    id: 23,
    nom: "Mebaley Ella",
    prenom: "Franck Junior",
    age: 26,
    ecole: "ISSEA",
    niveau: "M1 Statistiques",
    quartier: "Avorbam",
  },
  {
    id: 24,
    nom: "Nguema Obiang",
    prenom: "Clarisse Mireille",
    age: 25,
    ecole: "HEM",
    niveau: "M2 CCA",
    quartier: "Beau-Séjour",
  },
  {
    id: 25,
    nom: "Allogo Minko",
    prenom: "Christian Brice",
    age: 28,
    ecole: "SUP Telecom",
    niveau: "M2 Cybersécurité",
    quartier: "Okala",
  },
  {
    id: 26,
    nom: "Ovono Nkoghe",
    prenom: "Henriette Solange",
    age: 24,
    ecole: "ISP",
    niveau: "L3 Histoire",
    quartier: "Ntoum",
  },
  {
    id: 27,
    nom: "Ndong Ella",
    prenom: "Maurice Arnaud",
    age: 29,
    ecole: "UOB",
    niveau: "M1 Économie",
    quartier: "Bikélé",
  },
  {
    id: 28,
    nom: "Mengara Nguema",
    prenom: "Prisca Nadège",
    age: 22,
    ecole: "ENS",
    niveau: "L2 Sciences",
    quartier: "Cap Estérias",
  },
  {
    id: 29,
    nom: "Minko Obiang",
    prenom: "Lionel Bertrand",
    age: 30,
    ecole: "Polytech",
    niveau: "M2 Génie Logiciel",
    quartier: "Nzeng-Ayong",
  },
  {
    id: 30,
    nom: "Akoumba Ella",
    prenom: "Chanelle Christelle",
    age: 23,
    ecole: "HEM",
    niveau: "M1 Gestion",
    quartier: "Louis",
  },
  {
    id: 31,
    nom: "Ekang Ndong",
    prenom: "Rufin Serge",
    age: 26,
    ecole: "SUP Management",
    niveau: "M1 Commerce",
    quartier: "Aéroport",
  },
  {
    id: 32,
    nom: "Essone Obame",
    prenom: "Stéphanie Mireille",
    age: 25,
    ecole: "UOB",
    niveau: "L3 Communication",
    quartier: "Owendo",
  },
  {
    id: 33,
    nom: "Biyogo Ella",
    prenom: "Emmanuel Pierre",
    age: 28,
    ecole: "ENSET",
    niveau: "M2 Génie Mécanique",
    quartier: "Melen",
  },
  {
    id: 34,
    nom: "Mvong Ella",
    prenom: "Dorine Clarisse",
    age: 24,
    ecole: "HEM",
    niveau: "M1 Comptabilité",
    quartier: "Belle-Vue 1",
  },
  {
    id: 35,
    nom: "Mengue Ndong",
    prenom: "Grégoire Thierry",
    age: 27,
    ecole: "ISSEA",
    niveau: "M2 Statistiques",
    quartier: "Okala",
  },
  {
    id: 36,
    nom: "Allogo Nna",
    prenom: "Judith Grâce",
    age: 22,
    ecole: "ENS",
    niveau: "L3 Littérature",
    quartier: "Nzeng-Ayong",
  },
  {
    id: 37,
    nom: "Obiang Mengue",
    prenom: "Gaël Romaric",
    age: 29,
    ecole: "Polytech",
    niveau: "M2 Informatique",
    quartier: "Sotega",
  },
  {
    id: 38,
    nom: "Ella Nkoghe",
    prenom: "Sandrine Paulette",
    age: 25,
    ecole: "ISP",
    niveau: "M1 Sociologie",
    quartier: "Batterie IV",
  },
  {
    id: 39,
    nom: "Ndong Ovono",
    prenom: "Christel Adrien",
    age: 26,
    ecole: "HEM",
    niveau: "M1 Audit",
    quartier: "Mikolongo",
  },
  {
    id: 40,
    nom: "Nguema Ella",
    prenom: "Caroline Divine",
    age: 23,
    ecole: "UOB",
    niveau: "L2 Géographie",
    quartier: "Akournam",
  },
  {
    id: 41,
    nom: "Nziengui Obame",
    prenom: "Ulrich Boris",
    age: 28,
    ecole: "BBS",
    niveau: "M1 Informatique",
    quartier: "Cap Caravane",
  },
  {
    id: 42,
    nom: "Ovono Mengara",
    prenom: "Eunice Joëlle",
    age: 24,
    ecole: "ENAM",
    niveau: "M1 Gestion",
    quartier: "Sotega",
  },
  {
    id: 43,
    nom: "Ella Mbadinga",
    prenom: "Patrice Junior",
    age: 29,
    ecole: "SUP Telecom",
    niveau: "M2 Réseaux",
    quartier: "Okala",
  },
  {
    id: 44,
    nom: "Mba Ndong",
    prenom: "Clarisse Nadine",
    age: 22,
    ecole: "ISP",
    niveau: "L3 Philosophie",
    quartier: "Nzeng-Ayong",
  },
  {
    id: 45,
    nom: "Edzang Ella",
    prenom: "Thierry Cédric",
    age: 27,
    ecole: "HEM",
    niveau: "M1 CCA",
    quartier: "Melen",
  },
  {
    id: 46,
    nom: "Ovono Nna",
    prenom: "Josiane Mireille",
    age: 25,
    ecole: "UOB",
    niveau: "M2 Économie",
    quartier: "Belle-vue 2",
  },
  {
    id: 47,
    nom: "Mengara Obiang",
    prenom: "Brice Junior",
    age: 28,
    ecole: "Polytech",
    niveau: "M2 Électronique",
    quartier: "Glass",
  },
  {
    id: 48,
    nom: "Ella Obiang",
    prenom: "Tatiana Christelle",
    age: 24,
    ecole: "BBS",
    niveau: "M1 Management",
    quartier: "Louis",
  },
  {
    id: 49,
    nom: "Ndong Mengome",
    prenom: "Franck Arnaud",
    age: 26,
    ecole: "ENS",
    niveau: "M2 Sciences",
    quartier: "Okala",
  },
  {
    id: 50,
    nom: "Obame Ella",
    prenom: "Sylvain Rodrigue",
    age: 30,
    ecole: "UOB",
    niveau: "M2 Droit",
    quartier: "Owendo",
  },
];

const dataActions = [
  { id: 1, label: "Exporter en csv", icone: <File size={16} />, className: "" },
  { id: 2, label: "Partager", icone: <Share size={16} />, className: "" },
  { id: 3, label: "Archiver", icone: <Archive size={16} />, className: "" },
  {
    id: 4,
    label: "Supprimer",
    icone: <X size={16} />,
    className: "texte-couleur-rouge-vif te-noir",
  },
];

const dataStyle = [
  { id: 1, classe: ".data[]", style: "Liste de data" },
  { id: 2, classe: ".actions[]", style: "Liste des actions" },
  { id: 3, classe: ".conteneurClassName", style: "Style du conteneur" },
  { id: 4, classe: ".maxHeight", style: "Hauteur maximale " },
];

export default function TableauPage() {
  return (
    <>
      <TitreDoc
        titre={"Tableau"}
        icone={<TableIcon size={20} className="texte-couleur-bleu-ciel" />}
      />

      <Col className={"mh-5 gap-6"}>
        <Bloc type={"myn"} nombre={11} className={"texte-couleur-gris mb-6"}>
          <p>
            Un tableau sert à organiser et afficher des données sous forme de
            lignes et de colonnes, afin de faciliter la lecture, la comparaison
            et la gestion des informations.
          </p>
        </Bloc>

        <Tableau data={dataStyle} titre1={"props"} titre2={"rôle"} />
        <h3>Exemple</h3>
        <Table
          maxHeight={400}
          data={dataTest}
          titre={"Mon tableau"}
          label={"Actions"}
          actions={dataActions}
          conteneurClassName={"bloc-myn-11"}
        />
      </Col>
    </>
  );
}
